version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: taskflow-backend
    environment:
      - DATABASE_URL=${DATABASE_URL:-}
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
    volumes:
      - backend_data:/app/data
    networks:
      - taskflow-network

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_APP_NAME=TaskFlow
    container_name: taskflow-frontend
    depends_on:
      - backend
    networks:
      - taskflow-network

volumes:
  backend_data:
    driver: local

networks:
  taskflow-network:
    driver: bridge